### ISSUE TITLE
Issues with deb12 box image

### ISSUE THREAD

**Issue by sriharsha-github** [naveenrajm7/utm-box#1]
Hi Naveen,
Thanks for this plugin its very useful.
I noticed a couple of issues with deb12 box image:
1. Network connection issue: `vagrant up` is not able to establish ssh connection to VM
    * Fix: add a new network interface, with network mode set to `Emulated VLAN` and add the following lines to `/etc/network/interfaces` at the end:
```
allow-hotplug eth1
iface eth1 inet dhcp
```
2. The VM does not start in headless mode
    * Fix: I update the serial port mode to `Pseduo-TTY Device`

**Comment by naveenrajm7** [comment]
Hello Sri Harsha!

Thanks a lot for trying out this plugin and reporting this issue.

Since I used debian11 in all my tests and examples, debian12 box didn't get the attention it needed. 
I appreciate your effort in providing the solutions for these issues. 

I have decided that rather than building more UTM boxes (.utm file), it is worthwhile to spend that effort to add UTM import and Vagrant box support. Once these are available we can use Vagrant cloud and also avoid downloading box for every vagrant up execution.

Having said that, your fixes will come in handy when I build Debian and other Linux Vagrant boxes.

Thanks!

**Comment by egandro** [comment]
Do you guys need help here?

**Comment by naveenrajm7** [comment]
Hi @egandro 
Thanks for offering help.
With [new plugin release](https://github.com/naveenrajm7/vagrant_utm/releases/tag/v0.1.1) which supports Vagrant boxes, I am dropping support for the above mentioned Debian UTM zip box.

However, I am currently in the process of building a Debian 12 image in Vagrant box format through a different approach, which I will soon share.
Maybe you can help us when you try out our new Debian 12 vagrant box.

I will keep this issue open, until new Debian 12 box is out.

**Comment by naveenrajm7** [comment]
Hello,

I am trying to use cloud images to produce vagrant boxes, 
Does anyone know how to configure the above-mentioned dhcp setting throug cloud config seed file ? 

```yaml
#cloud-config
hostname: debian
users:
  - name: vagrant
    gecos: Vagrant User
    shell: /bin/bash
    homedir: /home/vagrant
    ...
```

Currently, the interface doesn't get IP address and hence  the port forwarding is not working.
If anyone knows please share.

**Comment by naveenrajm7** [comment]
Okay there was a cloud-init bug, I have fixed it with a workaround.

**Comment by naveenrajm7** [comment]
@sriharsha-github  Thanks for your fixes, It helped to address IP, and port-forwarding issues with the VMs.

I have now fully automated UTM box creation, and am using cloud images for distros which provide qemu cloud images.

Just released the  Debian 12 box with the name bookworm (a convention I'll use to indicate cloud images)

You can start using now

```
vagrant init utm/bookworm
```

Please share your feedback
